name: 上报 Bug
description: 使用中文进行 Bug 报告
labels: ['bug']
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前...
      options:
      - label: 我已经搜索了现有的 issues, discussions
        required: true
      - label: 我在提问题之前至少花费了 5 分钟来思考和准备
        required: true
      - label: 我已经阅读了 Wiki 中的 常见问题(FAQ)
        required: true
      - label: 我正在使用最新版的 Alas，如果不是，请在下面提供正在使用的 commit signature.
        required: false
  - type: textarea
    id: describe
    attributes:
      label: 描述你的问题
      description: 简要描述你的问题
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 如何复现
      description: 重现该行为的步骤
      placeholder: |
        1. 前往 '...'
        2. 点击 '....'
        3. 滑动到 '....'
        4. 出现问题
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 预期行为
      description: 简要描述你期望发生的事情
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 相关 Logs
      description: 请复制并粘贴任何相关的日志输出。
      placeholder: |
        上传出错 log，在 log/error 目录下，以毫秒时间戳为文件夹名，包含 log.txt 和最近的截图。
        若不是错误而是非预期的行为，提供在 log 目录下当天的 log 和至少一张游戏截图。
      render: shell
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: |
        如果有，添加屏幕截图以帮助解释你的问题。
        提示: 可以通过点击这个区域，然后把文件拖进来添加图片或日志文件。
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: 还有别的吗？
      description: |
        相关的配置？链接？参考资料？
        任何能让我们对你所遇到的问题有更多了解的东西。
    validations:
      required: false
  - type: checkboxes
    id: final_check
    attributes:
      label: 最后确认
      description: 不遵守规范的 issue 可能会被**直接关闭**
      options:
      - label: 我确保我提供了相关 log 或 其他能够帮助解决问题的信息
        required: true
      - label: 提交这个 issue 意味着我已经阅读并同意遵守 Alas 社区准则 https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1418
        required: true
