name: 功能请求
description: 使用中文进行功能请求
labels: ['feature']
body:
  - type: textarea
    id: describe
    attributes:
      label: 你的功能请求是否与某个问题有关？
      description: 简要描述相关的问题
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: 解决方案
      description: 描述你想要的解决方案或期望
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: 其他内容
      description: 关于该功能请求的任何其他背景或屏幕截图。
    validations:
      required: false
  - type: checkboxes
    id: final_check
    attributes:
      label: 最后确认
      description: 不遵守规范的 issue 可能会被**直接关闭**
      options:
      - label: 我确保这是一个新功能请求而不是一个 bug 报告
        required: true
      - laben: 我确保提供了详细的功能需求或相关的解决方案
        required: true
      - label: 提交这个 issue 意味着我已经阅读并同意遵守 Alas 社区准则 https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1418
        required: true
