name: Feature request
description: Suggest an idea for this project
labels: ['feature']
body:
  - type: textarea
    id: describe
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: Ex. I'm always frustrated when ...
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: final_check
    attributes:
      label: Final check
      description: We may close your issue if it doesn't meets the specification.
      options:
      - label: I am sure this is a feature request, not bug report
        required: true
      - label: I provide my requirements or relevant solutions in detail
        required: true
      - label: By submitting this issue, I agree to follow [Alas Community Guidelines](https://github.com/LmeSzinc/AzurLaneAutoScript/issues/1418)
        required: true
